"""
Wittgenstein Table — the GEM Translation Layer.

"The limits of my language mean the limits of my world." — Wittgenstein

This table is not a constraint, it's a TRANSLATION.
It does not restrict what enters — it defines how anything entering
becomes internally representable in GEM's formal grammar.

Every signal from the outside world passes through this table.
The table generates STRUCTURAL SIGNATURES, not subjective labels.
Two signals that produce the same signature are structurally equivalent
in GEM's internal grammar — not just "similar" by our judgment.

This is the core of the GEM design philosophy:
  The observer does not name structures.
  The translation layer names them.
  The observer understands the names.
"""

from __future__ import annotations
from typing import List, Dict, Tuple, Optional
from dataclasses import dataclass


@dataclass
class Translation:
    """One entry in the Wittgenstein Table."""
    external: str         # the raw input encoding
    internal: str         # the GN-encoded formula structure
    signature: str        # the structural signature generated by the table
    domain: str           # which grammar domain this falls into


class WittgensteinTable:
    """Translation layer between raw input and GEM's formal grammar.
    
    Every signal entering GEM passes through this table.
    The table generates structural signatures based on the
    formula tree — not on human labeling.
    
    The table is extensible: new domains can be added without
    modifying existing ones.
    """
    
    def __init__(self):
        self._translations: List[Translation] = []
        self._domains = set()
    
    def translate(self, raw_input: str) -> Translation:
        """Translate raw input into a GEM-internal representation.
        
        This is the ONLY entry point for external signals.
        """
        # Generate internal representation and signature
        internal, signature, domain = self._encode(raw_input)
        entry = Translation(
            external=raw_input,
            internal=internal,
            signature=signature,
            domain=domain,
        )
        self._translations.append(entry)
        self._domains.add(domain)
        return entry
    
    def _encode(self, raw: str) -> Tuple[str, str, str]:
        """Encode raw input -> internal representation + signature + domain.
        
        This is where the actual structural analysis happens.
        Not subjective labeling — objective tree traversal
        producing the system's internal canonical name.
        """
        # Detect domain
        if self._is_arithmetic(raw):
            domain = "arithmetic"
            internal, signature = self._encode_arithmetic(raw)
        elif self._is_geometric(raw):
            domain = "geometric"
            internal, signature = self._encode_geometric(raw)
        else:
            domain = "raw"
            internal, signature = self._encode_raw(raw)
        
        return internal, signature, domain
    
    def _is_arithmetic(self, raw: str) -> bool:
        return any(sym in raw for sym in ["+","×","forall","exists","="])
    
    def _is_geometric(self, raw: str) -> bool:
        return any(sym in raw for sym in ["point","line","between","cong"])
    
    def _encode_arithmetic(self, raw: str) -> Tuple[str, str]:
        """Encode arithmetic formula -> internal + signature."""
        import re
        # Extract structural components
        quantifiers = ["forall" for _ in re.findall(r"∀", raw)]
        operators = re.findall(r"[+\×]", raw)
        has_equation = "=" in raw
        has_swap = raw.count("+") >= 2 and "+" in raw.split("=")[0] and "+" in raw.split("=")[1]
        
        internal = raw  # simplified — in production this would be full GN encoding
        parts = quantifiers + (["equation"] if has_equation else [])
        parts.extend(["add"] if "+" in operators else [])
        parts.extend(["mul"] if "×" in operators else [])
        if has_swap:
            parts.append("swap")
        
        return internal, "_".join(parts)
    
    def _encode_geometric(self, raw: str) -> Tuple[str, str]:
        """Encode geometric formula."""
        return raw, "geometric_" + raw[:20]
    
    def _encode_raw(self, raw: str) -> Tuple[str, str]:
        """Encode raw (non-domain) input."""
        # UTF encoding for raw characters
        code = ord(raw[0]) if raw else 0
        cls = "upper" if 65 <= code <= 90 else "lower" if 97 <= code <= 122 else "digit" if 48 <= code <= 57 else "symbol"
        return f"GN({code})", f"raw_{cls}"
    
    def domains(self) -> List[str]:
        """Return all discovered grammar domains."""
        return sorted(self._domains)
    
    def domain_frequencies(self) -> Dict[str, int]:
        """Count translations per domain."""
        from collections import Counter
        return dict(Counter(t.domain for t in self._translations))
    
    def report(self) -> str:
        """Generate a human-readable translation report."""
        lines = ["Wittgenstein Table — Translation Log"]
        lines.append(f"  {'Domain':<12} {'Count':<8} {'External → Internal → Signature'}")
        lines.append(f"  {'-'*60}")
        
        from collections import Counter
        by_domain = {}
        for t in self._translations:
            if t.domain not in by_domain:
                by_domain[t.domain] = []
            by_domain[t.domain].append(t)
        
        for domain, entries in sorted(by_domain.items()):
            lines.append(f"  {domain:<12} {len(entries):<8}")
            shown = set()
            for e in entries[:3]:
                key = e.signature
                if key not in shown:
                    lines.append(f"    {e.external[:30]:<30} -> {e.signature}")
                    shown.add(key)
            if len(shown) < len(set(e.signature for e in entries)):
                lines.append(f"    ... and {len(entries)-len(shown)} more entries")
        
        lines.append(f"\n  Total domains: {len(self._domains)}")
        lines.append(f"  Total translations: {len(self._translations)}")
        lines.append(f"\n  This table is a TRANSLATION layer, not a filter.")
        lines.append(f"  All inputs are accepted. The table determines how")
        lines.append(f"  each input maps to GEM's internal grammar.")
        return "\n".join(lines)
