"""
Numerical Turing Test: GEME distinguishes human from machine text.

Design (following S3 Hammurabi's methodology):
  - Input unit: 4-5 word window (natural working memory span)
  - Each window encoded as character-bigram frequency → 27-dim
  - Paired texts: same topic, one human-written, one LLM-generated
  - Hypothesis: frame-economic metrics differ between human and machine text

Domains:
  - Human answers vs LLM answers (TruthfulQA pairs)
  - Human summaries vs LLM summaries (CNN/DailyMail style)
  - Wikipedia (human) vs LLM-completed Wikipedia paragraphs
"""
import sys, math, json
sys.path.insert(0, '../code')
from geme import GEME, _VEC_DIM
from collections import Counter


def build_bigram_map(texts, top_n=27):
    counts = Counter()
    for t in texts:
        tl = t.lower()
        for i in range(len(tl) - 1):
            counts[tl[i:i+2]] += 1
    top = [bg for bg, _ in counts.most_common(top_n)]
    return {bg: i for i, bg in enumerate(top)}


def window_encode(window, bg_map):
    """Encode a 4-5 word window as a 27-dim bigram frequency vector."""
    text = ' '.join(window).lower()
    vec = [0.0] * _VEC_DIM
    total = 0
    for i in range(len(text) - 1):
        bg = text[i:i+2]
        if bg in bg_map:
            vec[bg_map[bg]] += 1.0
            total += 1
    if total > 0:
        vec = [v / total for v in vec]
    return vec


def chunk_text(text, window_size=5):
    """Split text into overlapping 5-word windows (slide by 2 words)."""
    words = text.split()
    windows = []
    for i in range(0, max(1, len(words) - window_size + 1), 2):
        windows.append(words[i:i+window_size])
    return windows


def process_text(text, bg_map, capacity=16):
    """Feed text windows through GEME, return frame-economic metrics."""
    g = GEME(memory_cap=capacity)
    g.memory.preserve_sig = True
    g.memory.quantum_mode = True
    g.memory.cooccur_thresh = 0.08

    windows = chunk_text(text, window_size=5)
    if len(windows) < 3:
        return None

    acc_history = []
    for w in windows:
        vec = window_encode(w, bg_map)
        g.process_vec(vec, ' '.join(w[:3]))

        # Periodic induction
        if len(windows) > 10:
            g.memory.induction_clean() if len(windows) % 10 == 9 else None

    m = g.metrics()
    return {
        'frame_count': m.get('frame_count', 0),
        'total_weight': round(m.get('total_weight', 0), 2),
        'efficiency': m.get('efficiency', 0.0),
        'stress': m.get('stress', 0.0),
        'entropy': m.get('structural_entropy', 0.0),
        'L4': m.get('L4_frame_count', 0),
        'preds': m.get('pred_total', 0),
        'accuracy': m.get('pred_accuracy', 0.0),
        'conf_threshold': m.get('conf_threshold', 0.0),
        'I_phi_X': m.get('I(phi;X)', 0.0),
        'layers': m.get('layers', {}),
        'n_windows': len(windows),
    }


# ============================================================
# Stimuli: human vs machine text pairs on same topics
# ============================================================
# Each pair: same topic, ~100 words each, one human one synthetic
# Human: from Wikipedia or human-written
# Machine: generated by LLM (simulated here with known LLM patterns)

TEXT_PAIRS = [
    {
        "topic": "moon_landing",
        "human": (
            "The Apollo 11 mission landed the first humans on the Moon "
            "on July 20 1969. Commander Neil Armstrong and lunar module "
            "pilot Buzz Aldrin formed the American crew that landed the "
            "Apollo Lunar Module Eagle. Armstrong became the first person "
            "to step onto the lunar surface six hours and thirty nine minutes "
            "after landing on July 21. He described the event as one small "
            "step for man one giant leap for mankind. Aldrin joined him "
            "nineteen minutes later and they spent about two and a quarter "
            "hours together exploring the site they had named Tranquility "
            "Base upon landing. They collected forty seven and a half pounds "
            "of lunar material to bring back to Earth."
        ),
        "machine": (
            "The historic Apollo 11 mission successfully achieved the first "
            "human moon landing on July 20 1969 representing a monumental "
            "achievement in space exploration and human endeavor. Commander "
            "Neil Armstrong accompanied by lunar module pilot Buzz Aldrin "
            "executed a precise landing of the Eagle module on the lunar "
            "surface demonstrating remarkable technological prowess. Armstrong "
            "subsequently became the inaugural human to traverse the moon "
            "surface delivering his iconic proclamation regarding steps and "
            "mankind. The mission comprehensively gathered scientific samples "
            "and conducted extensive experiments that significantly advanced "
            "human understanding of lunar geology and composition."
        ),
    },
    {
        "topic": "climate_change",
        "human": (
            "Climate change includes both global warming driven by human "
            "emissions of greenhouse gases and the resulting large scale "
            "shifts in weather patterns. Though there have been previous "
            "periods of climatic change since the mid twentieth century "
            "humans have had an unprecedented impact on Earth s climate "
            "system and caused change on a global scale. The largest driver "
            "of warming is the emission of gases that create a greenhouse "
            "effect of which more than ninety percent are carbon dioxide "
            "and methane. Fossil fuel burning for energy consumption is "
            "the main source of these emissions with additional contributions "
            "from agriculture deforestation and manufacturing."
        ),
        "machine": (
            "Climate change represents one of the most pressing challenges "
            "facing contemporary global society characterized by rising "
            "temperatures and increasingly volatile meteorological phenomena. "
            "The scientific consensus overwhelmingly attributes these "
            "environmental transformations to anthropogenic activities "
            "particularly the emission of greenhouse gases from industrial "
            "processes and transportation systems. Addressing this multifaceted "
            "crisis requires comprehensive international cooperation and "
            "the implementation of sustainable practices across all sectors "
            "of the global economy. The transition toward renewable energy "
            "sources constitutes a critical component of any effective "
            "mitigation strategy for ensuring long term environmental stability."
        ),
    },
    {
        "topic": "coffee_preparation",
        "human": (
            "To make a good cup of coffee start with fresh beans. Grind them "
            "just before brewing if you can. The grind size matters a lot. "
            "Too fine and your coffee will be bitter. Too coarse and it will "
            "be weak and sour. For a standard drip machine use a medium grind "
            "about the texture of sand. Use about two tablespoons of ground "
            "coffee per six ounces of water. The water should be hot but not "
            "boiling right around two hundred degrees. If your tap water "
            "tastes bad your coffee will too so use filtered water. Pour "
            "slowly and let the grounds bloom for about thirty seconds first."
        ),
        "machine": (
            "The preparation of optimal coffee beverages necessitates careful "
            "attention to multiple parameters including grind consistency "
            "water temperature and extraction methodology. Fresh grinding "
            "of premium coffee beans immediately prior to the brewing process "
            "ensures maximum flavor compound preservation. The precise "
            "calibration of grind particle size distribution profoundly "
            "influences the extraction kinetics and resultant organoleptic "
            "properties of the final beverage. Water quality considerations "
            "extend beyond mere filtration to encompass mineral content "
            "optimization for ideal extraction dynamics across various "
            "brewing modalities and preparation techniques."
        ),
    },
    {
        "topic": "walking_dog",
        "human": (
            "I take my dog out every morning around seven. She pulls on the "
            "leash when she sees squirrels. There is this one oak tree on "
            "the corner where squirrels always hang out and she goes nuts "
            "every single time. I have to brace myself or she will yank my "
            "arm right out of the socket. After the squirrel spot we walk "
            "past the old church and she calms down a bit. She sniffs the "
            "same fire hydrant every day like it is the most interesting "
            "thing in the world. Dogs are weird like that. By the time we "
            "get home she is tired and happy and so am I."
        ),
        "machine": (
            "The daily routine of canine exercise represents an essential "
            "component of responsible pet ownership providing both physical "
            "stimulation and psychological enrichment for domesticated dogs. "
            "Morning walks facilitate cardiovascular health maintenance while "
            "simultaneously addressing the behavioral requirements of various "
            "breeds through exposure to diverse environmental stimuli. The "
            "interaction between canine companions and their surroundings "
            "during these excursions generates opportunities for socialization "
            "and olfactory exploration which constitute fundamental aspects "
            "of canine cognitive and emotional wellbeing. Regular walking "
            "schedules furthermore strengthen the human animal bond."
        ),
    },
    {
        "topic": "child_birthday",
        "human": (
            "My daughter turned six last Saturday. We got a cake from the "
            "bakery down the street with pink frosting and little unicorns "
            "on it. She was so excited she could barely sit still while we "
            "sang happy birthday. Her little brother tried to blow out the "
            "candles before she could and she got mad and pushed him. Then "
            "he started crying and I had to separate them. After that they "
            "were fine. They ran around the yard with the other kids for "
            "two hours straight. By seven o clock she was passed out on "
            "the couch still wearing her party hat. Best birthday ever she "
            "whispered before falling asleep."
        ),
        "machine": (
            "The celebration of a child s sixth birthday constitutes a "
            "significant developmental milestone that merits comprehensive "
            "planning and execution of age appropriate festivities. The "
            "procurement of a thematically suitable confectionery product "
            "from a local bakery establishment serves as a central element "
            "of the celebratory experience. Sibling dynamics during such "
            "gatherings often manifest in predictable patterns of competitive "
            "behavior that require measured parental intervention strategies. "
            "Physical activity and social interaction among peer attendees "
            "contribute positively to the overall success of the event. "
            "The culmination of the celebration typically results in notable "
            "fatigue among younger participants indicative of a satisfactory "
            "experiential outcome."
        ),
    },
    {
        "topic": "repairing_sink",
        "human": (
            "The sink was leaking so I got under there with a wrench. Took "
            "me about twenty minutes to figure out which pipe was the problem. "
            "Turns out the gasket was shot completely dried out and cracked. "
            "I went to the hardware store and the guy there said I needed "
            "a half inch rubber gasket which of course they were out of. "
            "So I had to drive to the other store across town. Got the part "
            "came back and installed it. The hardest part was getting the "
            "old gasket off because it was basically fused to the pipe. "
            "Had to scrape it with a knife. But once the new one was in "
            "and I tightened everything back up no more leak. Took three "
            "hours for what should have been a fifteen minute job."
        ),
        "machine": (
            "The resolution of residential plumbing malfunctions requires "
            "systematic diagnostic procedures to identify the specific "
            "source of water leakage within the fixture assembly. Upon "
            "identification of the compromised sealing component the "
            "procurement of an appropriate replacement part from a hardware "
            "retail establishment becomes necessary for successful repair "
            "implementation. The removal of deteriorated sealing materials "
            "often presents technical challenges requiring specialized "
            "techniques and appropriate tools to ensure complete extraction "
            "without damage to adjacent components. Proper installation "
            "of the replacement component followed by thorough testing "
            "verifies the efficacy of the repair intervention."
        ),
    },
    {
        "topic": "recipe_failure",
        "human": (
            "I tried to make my grandmother s bread recipe last weekend. "
            "She never wrote it down properly so I was working from memory. "
            "The dough seemed too wet so I kept adding flour. Then it was "
            "too dry so I added more water. Then too wet again. I probably "
            "added flour three or four times before I gave up and just put "
            "it in the oven. What came out was less like bread and more "
            "like a brick. My husband tried to be nice about it. He said "
            "it would make good croutons which is code for this is inedible. "
            "I am going to call my grandmother and get the real recipe."
        ),
        "machine": (
            "The endeavor to replicate traditional family recipes without "
            "precise documentation often results in suboptimal outcomes due "
            "to the inherent challenges of estimating ingredient proportions "
            "and processing parameters from memory alone. The iterative "
            "adjustment of flour to water ratios exemplifies the difficulties "
            "encountered when attempting to achieve optimal dough consistency "
            "through empirical correction methods. The resultant baked product "
            "may deviate substantially from intended textural and organoleptic "
            "characteristics. The experience underscores the importance of "
            "precise recipe documentation for the preservation of culinary "
            "traditions across generations."
        ),
    },
]


if __name__ == '__main__':
    print("=" * 70)
    print("Numerical Turing Test: Human vs Machine Text")
    print("GEME frame-economic metrics on paired text (same topic)")
    print("=" * 70)

    # Build bigram map from ALL texts
    all_text = []
    for pair in TEXT_PAIRS:
        all_text.append(pair['human'])
        all_text.append(pair['machine'])
    bg_map = build_bigram_map(all_text, top_n=_VEC_DIM)

    human_results = []
    machine_results = []

    print(f"\n{'Topic':<22} {'Type':>7} {'Frames':>7} {'Entropy':>8} {'Eff':>7} {'L4':>4} {'Preds':>6} {'Acc':>6} {'I(phi;X)':>9}")
    print("-" * 78)

    for pair in TEXT_PAIRS:
        for source in ['human', 'machine']:
            text = pair[source]
            metrics = process_text(text, bg_map)
            if metrics is None:
                continue

            row = metrics
            if source == 'human':
                human_results.append(row)
            else:
                machine_results.append(row)

            tag = "HUMAN" if source == 'human' else "MACHINE"
            print(f"{pair['topic']:<22} {tag:>7} {row['frame_count']:7d} "
                  f"{row['entropy']:8.4f} {row['efficiency']:7.4f} "
                  f"{row['L4']:4d} {row['preds']:6d} {row['accuracy']:6.3f} "
                  f"{row['I_phi_X']:9.6f}")

    # Aggregate
    def avg(metrics_list, key):
        vals = [m[key] for m in metrics_list]
        return sum(vals) / len(vals) if vals else 0

    def avg_signed(key, higher_expected='human'):
        ha = avg(human_results, key)
        ma = avg(machine_results, key)
        if higher_expected == 'human':
            return ha, ma, ha - ma, "H>M [OK]" if ha > ma else "H<M"
        else:
            return ha, ma, ma - ha, "M>H [OK]" if ma > ha else "M<H"

    print(f"\n{'='*70}")
    print("AGGREGATE COMPARISON")
    print(f"{'='*70}")
    print(f"{'Metric':<20} {'Human':>8} {'Machine':>8} {'Delta':>8} {'Direction':>8}")
    print("-" * 58)

    comparisons = [
        ('frame_count', 'higher'),
        ('entropy', 'lower'),      # human text should be more structured
        ('efficiency', 'higher'),  # human text easier to model
        ('L4', 'higher'),          # more self-referential activity?
        ('preds', 'higher'),       # more predictions = more structure
        ('accuracy', 'higher'),    # easier to predict
        ('I_phi_X', 'lower'),      # tighter coupling self/world
    ]

    for key, direction in comparisons:
        ha, ma, delta, symbol = avg_signed(key,
            'human' if direction == 'higher' else 'machine')
        print(f"{key:<20} {ha:8.4f} {ma:8.4f} {delta:+8.4f} {symbol:>8}")

    # Effect size check
    if human_results and machine_results:
        he = avg(human_results, 'entropy')
        me = avg(machine_results, 'entropy')
        print(f"\n  Key prediction: LLM text should have HIGHER structural entropy")
        print(f"  (more formulaic structure = more predictable = higher frame entropy)")
        print(f"  Human entropy: {he:.4f}  Machine entropy: {me:.4f}")
        if me > he:
            print(f"  [CONFIRMED] Machine text entropy higher by {me-he:+.4f}")
        else:
            print(f"  [REVERSED] Human text entropy higher by {he-me:+.4f}")

    print(f"\n  Note: This is a proof-of-concept with 7 text pairs.")
    print(f"  A full experiment would use hundreds of pairs with controlled length.")
